# Generated by Django 3.0 on 2023-11-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serailapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serail',
            name='img',
            field=models.ImageField(default='asadsad', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
